name: Build Analyzer App

on:
  push:
    branches:
      - main
      - dev-branch

jobs:
  build-analyzer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/analyzer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build analyzer app
        run: npm run build

      - name: Copy build to docs/analyzer
        run: |
          mkdir -p ../../docs/analyzer
          cp -r dist/* ../../docs/analyzer/

      - name: Commit and push docs/analyzer
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ../../docs/analyzer
          git commit -m "Update analyzer build [skip ci]" || echo "No changes to commit"
          git push
