name: Deploy to GitHub Pages
##This workflow deploys the app to GitHub Pages whenever there is a push to the main or dev-branch branches.
on:
  push:
    branches:
      - main
      - dev-branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (main app)
        run: npm ci

      - name: Build main app
        run: npm run build

      - name: Install dependencies (analyzer)
        working-directory: apps/analyzer
        run: npm ci

      - name: Build analyzer app
        working-directory: apps/analyzer
        run: npm run build -- --outDir=../../dist/analyzer

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
